/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sjkim.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Reply service. Represents a row in the &quot;SJKIM_Reply&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>sjkim.model.impl.ReplyModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>sjkim.model.impl.ReplyImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reply
 * @generated
 */
@ProviderType
public interface ReplyModel extends BaseModel<Reply> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reply model instance should use the {@link Reply} interface instead.
	 */

	/**
	 * Returns the primary key of this reply.
	 *
	 * @return the primary key of this reply
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reply.
	 *
	 * @param primaryKey the primary key of this reply
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the reply no of this reply.
	 *
	 * @return the reply no of this reply
	 */
	public long getReplyNo();

	/**
	 * Sets the reply no of this reply.
	 *
	 * @param replyNo the reply no of this reply
	 */
	public void setReplyNo(long replyNo);

	/**
	 * Returns the board no of this reply.
	 *
	 * @return the board no of this reply
	 */
	public long getBoardNo();

	/**
	 * Sets the board no of this reply.
	 *
	 * @param boardNo the board no of this reply
	 */
	public void setBoardNo(long boardNo);

	/**
	 * Returns the reply content of this reply.
	 *
	 * @return the reply content of this reply
	 */
	@AutoEscape
	public String getReplyContent();

	/**
	 * Sets the reply content of this reply.
	 *
	 * @param replyContent the reply content of this reply
	 */
	public void setReplyContent(String replyContent);

	/**
	 * Returns the reply content back up of this reply.
	 *
	 * @return the reply content back up of this reply
	 */
	@AutoEscape
	public String getReplyContentBackUp();

	/**
	 * Sets the reply content back up of this reply.
	 *
	 * @param replyContentBackUp the reply content back up of this reply
	 */
	public void setReplyContentBackUp(String replyContentBackUp);

	/**
	 * Returns the reply writer of this reply.
	 *
	 * @return the reply writer of this reply
	 */
	@AutoEscape
	public String getReplyWriter();

	/**
	 * Sets the reply writer of this reply.
	 *
	 * @param replyWriter the reply writer of this reply
	 */
	public void setReplyWriter(String replyWriter);

	/**
	 * Returns the reply parent reply no of this reply.
	 *
	 * @return the reply parent reply no of this reply
	 */
	public Long getReplyParentReplyNo();

	/**
	 * Sets the reply parent reply no of this reply.
	 *
	 * @param replyParentReplyNo the reply parent reply no of this reply
	 */
	public void setReplyParentReplyNo(Long replyParentReplyNo);

	/**
	 * Returns the reply level of this reply.
	 *
	 * @return the reply level of this reply
	 */
	public Long getReplyLevel();

	/**
	 * Sets the reply level of this reply.
	 *
	 * @param replyLevel the reply level of this reply
	 */
	public void setReplyLevel(Long replyLevel);

	/**
	 * Returns the reply write date of this reply.
	 *
	 * @return the reply write date of this reply
	 */
	public Date getReplyWriteDate();

	/**
	 * Sets the reply write date of this reply.
	 *
	 * @param replyWriteDate the reply write date of this reply
	 */
	public void setReplyWriteDate(Date replyWriteDate);

	/**
	 * Returns the reply update date of this reply.
	 *
	 * @return the reply update date of this reply
	 */
	public Date getReplyUpdateDate();

	/**
	 * Sets the reply update date of this reply.
	 *
	 * @param replyUpdateDate the reply update date of this reply
	 */
	public void setReplyUpdateDate(Date replyUpdateDate);

	/**
	 * Returns the reply delete yn of this reply.
	 *
	 * @return the reply delete yn of this reply
	 */
	@AutoEscape
	public String getReplyDeleteYN();

	/**
	 * Sets the reply delete yn of this reply.
	 *
	 * @param replyDeleteYN the reply delete yn of this reply
	 */
	public void setReplyDeleteYN(String replyDeleteYN);

}