/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package sjkim.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UploadFile service. Represents a row in the &quot;SJKIM_UploadFile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>sjkim.model.impl.UploadFileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>sjkim.model.impl.UploadFileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UploadFile
 * @generated
 */
@ProviderType
public interface UploadFileModel extends BaseModel<UploadFile> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a upload file model instance should use the {@link UploadFile} interface instead.
	 */

	/**
	 * Returns the primary key of this upload file.
	 *
	 * @return the primary key of this upload file
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this upload file.
	 *
	 * @param primaryKey the primary key of this upload file
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the upload file no of this upload file.
	 *
	 * @return the upload file no of this upload file
	 */
	public long getUploadFileNo();

	/**
	 * Sets the upload file no of this upload file.
	 *
	 * @param uploadFileNo the upload file no of this upload file
	 */
	public void setUploadFileNo(long uploadFileNo);

	/**
	 * Returns the upload file board no of this upload file.
	 *
	 * @return the upload file board no of this upload file
	 */
	public long getUploadFileBoardNo();

	/**
	 * Sets the upload file board no of this upload file.
	 *
	 * @param uploadFileBoardNo the upload file board no of this upload file
	 */
	public void setUploadFileBoardNo(long uploadFileBoardNo);

	/**
	 * Returns the upload file name of this upload file.
	 *
	 * @return the upload file name of this upload file
	 */
	@AutoEscape
	public String getUploadFileName();

	/**
	 * Sets the upload file name of this upload file.
	 *
	 * @param uploadFileName the upload file name of this upload file
	 */
	public void setUploadFileName(String uploadFileName);

	/**
	 * Returns the upload real file name of this upload file.
	 *
	 * @return the upload real file name of this upload file
	 */
	@AutoEscape
	public String getUploadRealFileName();

	/**
	 * Sets the upload real file name of this upload file.
	 *
	 * @param uploadRealFileName the upload real file name of this upload file
	 */
	public void setUploadRealFileName(String uploadRealFileName);

	/**
	 * Returns the upload file upload path of this upload file.
	 *
	 * @return the upload file upload path of this upload file
	 */
	@AutoEscape
	public String getUploadFileUploadPath();

	/**
	 * Sets the upload file upload path of this upload file.
	 *
	 * @param uploadFileUploadPath the upload file upload path of this upload file
	 */
	public void setUploadFileUploadPath(String uploadFileUploadPath);

	/**
	 * Returns the upload file mime type of this upload file.
	 *
	 * @return the upload file mime type of this upload file
	 */
	@AutoEscape
	public String getUploadFileMimeType();

	/**
	 * Sets the upload file mime type of this upload file.
	 *
	 * @param uploadFileMimeType the upload file mime type of this upload file
	 */
	public void setUploadFileMimeType(String uploadFileMimeType);

	/**
	 * Returns the upload file writer of this upload file.
	 *
	 * @return the upload file writer of this upload file
	 */
	@AutoEscape
	public String getUploadFileWriter();

	/**
	 * Sets the upload file writer of this upload file.
	 *
	 * @param uploadFileWriter the upload file writer of this upload file
	 */
	public void setUploadFileWriter(String uploadFileWriter);

	/**
	 * Returns the upload file write date of this upload file.
	 *
	 * @return the upload file write date of this upload file
	 */
	public Date getUploadFileWriteDate();

	/**
	 * Sets the upload file write date of this upload file.
	 *
	 * @param uploadFileWriteDate the upload file write date of this upload file
	 */
	public void setUploadFileWriteDate(Date uploadFileWriteDate);

	/**
	 * Returns the upload file update date of this upload file.
	 *
	 * @return the upload file update date of this upload file
	 */
	public Date getUploadFileUpdateDate();

	/**
	 * Sets the upload file update date of this upload file.
	 *
	 * @param uploadFileUpdateDate the upload file update date of this upload file
	 */
	public void setUploadFileUpdateDate(Date uploadFileUpdateDate);

}