package sjkim.web.constants;

/**
 * @author gplus
 */
public class SjkimWebCommandKeys {

	public static final String BOARD_VIEW_RENDER = "BOARD_VIEW_RENDER";
	public static final String BOARD_REGIST_RENDER = "BOARD_REGIST_RENDER";
	public static final String BOARD_REGIST_ACTION = "BOARD_REGIST_ACTION";
	public static final String BOARD_UPDATE_RENDER = "BOARD_UPDATE_RENDER";
	public static final String BOARD_UPDATE_ACTION = "BOARD_UPDATE_ACTION";
	public static final String BOARD_DELETE_ACTION = "BOARD_DELETE_ACTION";
	public static final String BOARD_REPLY_LIST_RESOURCE = "BOARD_REPLY_LIST_RESOURCE";
	public static final String BOARD_REPLY_REGIST_RESOURCE = "BOARD_REPLY_REGIST_RESOURCE";
	public static final String BOARD_REPLY_UPDATE_RESOURCE = "BOARD_REPLY_UPDATE_RESOURCE";
	public static final String BOARD_REPLY_DELETE_RESOURCE = "BOARD_REPLY_DELETE_RESOURCE";
	public static final String BOARD_RE_REPLY_LIST_RESOURCE = "BOARD_RE_REPLY_LIST_RESOURCE";
	public static final String BOARD_RE_REPLY_REGIST_RESOURCE = "BOARD_RE_REPLY_REGIST_RESOURCE";
	public static final String BOARD_RE_REPLY_UPDATE_RESOURCE = "BOARD_RE_REPLY_UPDATE_RESOURCE";
	public static final String BOARD_RE_REPLY_DELETE_RESOURCE = "BOARD_RE_REPLY_DELETE_RESOURCE";
	public static final String BOARD_FILE_DOWNLOAD_RESOURCE = "BOARD_FILE_DOWNLOAD_RESOURCE";
	public static final String BOARD_FILE_DELETE_RESOURCE = "BOARD_FILE_DELETE_RESOURCE";
	
	public static final String DATATYPE_LIST_RENDER = "DATATYPE_LIST_RENDER";
	public static final String DATATYPE_REGIST_RENDER = "DATATYPE_REGIST_RENDER";
	public static final String DATATYPE_REGIST_ACTION = "DATATYPE_REGIST_ACTION";
	public static final String DATATYPE_UPDATE_RENDER = "DATATYPE_UPDATE_RENDER";
	public static final String DATATYPE_UPDATE_ACTION = "DATATYPE_UPDATE_ACTION";
	public static final String DATATYPE_DELETE_ACTION = "DATATYPE_DELETE_ACTION";
	public static final String DATATYPE_VIEW_RENDER = "DATATYPE_VIEW_RENDER";
	public static final String DATATYPE_DUPLICATED_CHECK_RESOURCE = "DATATYPE_DUPLICATED_CHECK_RESOURCE";
	public static final String DATATYPE_CLONE_ACTION = "DATATYPE_CLONE_ACTION";
	public static final String DATATYPE_UPGRADE_ACTION = "DATATYPE_UPGRADE_ACTION";
	public static final String DATATYPE_JSON_FILE_DOWNLOAD_RESOURCE = "DATATYPE_JSON_FILE_DOWNLOAD_RESOURCE";
	public static final String DATATYPE_FILE_DOWNLOAD_RESOURCE = "DATATYPE_FILE_DOWNLOAD_RESOURCE";
	public static final String DATATYPE_FILE_DELETE_RESOURCE = "DATATYPE_FILE_DELETE_RESOURCE";

}